name: bili-action
description: Github Action for bilibili
author: kt

branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  bvid:
    description: video bvid
    required: false
  aid:
    description: video aid
    required: false
  cid:
    description: video cid
    required: false
  mid:
    description: |
      user mid, if bvid, aid and cid are not provided, 
      this will be used to get the user's latest video
    required: false
  keyword:
    description: |
      search keyword, use with `mid`, get user's latest video with keyword
    required: false
  batch:
    type: boolean
    default: false
    description:
      work with `mid` & `keyword`, get user's videos(max 1000) and set to batch
      output
  audio:
    description: upload audio
    required: false
  video:
    description: upload video
    required: false
  sessdata:
    description: |
      bilibili sessdata
    required: false
  proxy-stream-host:
    description: proxy stream api host, may return 404
    required: false
  audio-file-template:
    description: audio file path template, use python like formating
    required: false
  video-file-template:
    description: video file path template, use python like formating
    required: false
outputs:
  bvid:
    description: bvid
  aid:
    description: aid
  cid:
    description: bid
#  video:
#    description: video detail, a stringifies json object
#  batch:
#    description: videos, a stringifies json array
runs:
  using: node20
  main: dist/index.js
