name: bili-action
description: Github Action for bilibili
author: kt

branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  bvid:
    description: video bvid
    required: true

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js