name: Continuous Integration

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          aid: 114209723516061
      - name: Show Result
        run: |
          echo '${{steps.test-action.outputs.video}}'
          echo 'show top comment'
          echo '${{toJSON(fromJSON(steps.test-action.outputs.video).topComment)}}'

      - name: Test Download Local Action
        id: test-stream-action
        uses: ./
        with:
          proxy-stream-host: https://posh-stoat-85.deno.dev
          aid: 2325306
          audio: true
          audio-file-template: 'output/{bvid}.m4a'
      - name: Test Download Local Action
        uses: ./
        with:
          proxy-stream-host: https://posh-stoat-85.deno.dev
          bvid: BV1C6kvYDEWx
          audio: true
          audio-file-template: 'output/{bvid}.m4a'
      - name: Test Download Local Action
        id: test-get-stream-by-user-action
        uses: ./
        with:
          proxy-stream-host: https://posh-stoat-85.deno.dev
          mid: 316568752
          keyword: 睡前消息
          audio: true
          audio-file-template: 'output/{bvid}.m4a'
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: |
            output/*
      - name: Print Output
        id: output
        run: |
          echo '${{ steps.test-action.outputs.video }}'
