name: Continuous Integration

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          aid: 2325306

      #      - name: Test Download Local Action
      #        id: test-stream-action
      #        uses: ./
      #        with:
      #          aid: 2325306
      #          audio: true
      #
      - name: Test Download Local Action
        id: test-get-stream-by-user-action
        uses: ./
        with:
          proxy-stream-host: https://posh-stoat-85.deno.dev
          mid: 316568752
          keyword: 睡前消息
          audio: true

      - uses: actions/upload-artifact@v4
        with:
          name: output.audio.mp4
          path: |
            *.audio.mp4

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.bvid }}"
