name: Continuous Integration

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          cid: 3629601

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.aid }}"
